services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - main


networks:
  main:


volumes:
  mongodb: